### ISSUE TITLE
updated brood table missing stock.ID for new WCVI stocks

### ISSUE THREAD

**Issue by brendanmichaelconnors** [Pacific-salmon-assess/Salmon-warming-crowded-oceans#2]
The updated sockeye brood table ([here](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/blob/main/data-downloaded/raw_brood_table_2023_07_19.csv)) is missing Stock.ID for the new WCVI stocks and they should only have NAs in the age specific recruit columns (e.g., "R0.1") if the data are truly missing/do not exist, otherwise they should be zeros

**Comment by hvhunter** [comment]
Regarding the NAs - they are NA in the raw data but I suspect these are life histories they don't get, not missing data. Raw data file attached:
[Somass_stock_recruit_1977-2022.csv](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/files/12479288/Somass_stock_recruit_1977-2022.csv)

**Comment by brendanmichaelconnors** [comment]
Ok, thanks for confirming. These NAs should be replaced with 0s except at end of time series in instances where an observation is not possible (e.g., 6 year old recruits from 2018 brood year)

**Comment by hvhunter** [comment]
Thanks. I just fixed those columns. I'm a little lost with the Stock.ID numbering system, can you shed some light on that? Or just drop what the 2 new stock ids should be and I'll add them to the brood and info files.

**Comment by brendanmichaelconnors** [comment]
There is nothing particularly special to the stock ordering system. Though originally they went from south to north (approximately). 

I think you can just go with the stock numbers that are already in the [raw_stock_info_2023_06_18.csv](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/blob/main/data-downloaded/raw_stock_info_2023_06_18.csv) which would be 

- Great central = 1121
- Sproat = 122

but I am not 100% sure how you are handling ordering in plotting (is it just based on row order in file?) and so did not go in and make the change myself.

**Comment by hvhunter** [comment]
I didn't think to look if they already had one, thanks. They are ordered by latitude in a function which should still work. Closing as this should be resolved with the last commit.
