### ISSUE TITLE
cannot create directory for single stock models 

### ISSUE THREAD

**Issue by brendanmichaelconnors** [Pacific-salmon-assess/Salmon-warming-crowded-oceans#3]
Code [here](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/blob/b711c902a7fd03be093f30db6d75236047b6adea/stat_single_stock_fit.R#L33) results in this error:

![image](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/assets/31934797/a99961a8-d812-4976-9e51-2fd06fd2bef3)

not sure what is going on. For now manually overriding by creating directory locally.

update: also an issue for some other directories (e.g., './output/diagnostics/')

**Comment by hvhunter** [comment]
Works for me if you add another / after the folder name, i.e. 

if(!dir.exists("./output/models/stat/single-stock/")) dir.create("./output/models/stat/single-stock/")

**Comment by brendanmichaelconnors** [comment]
Well that was an easy fix, I have pushed to repo, thanks!
