### ISSUE TITLE
Cannot generate figures in "stat_hbm_inf.R"

### ISSUE THREAD

**Issue by brendanmichaelconnors** [Pacific-salmon-assess/Salmon-warming-crowded-oceans#4]
Error is being returned when trying to join single stock and hbm coefficient dataframes [here](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/blob/11e0d080561870a0682b32868017da154652577b/stat_hbm_inf.R#L208). Appears to be because the single stock dataframe does not have 'Stock' as an ordered factor:

![image](https://github.com/Pacific-salmon-assess/Salmon-warming-crowded-oceans/assets/31934797/d0db264d-4933-4c4c-b23c-621f55035afa)

**Comment by hvhunter** [comment]
I didn't get the same error when running this. I've added a line that makes 'ss.dat$Stock' an ordered factor anyway - hopefully that solves it.
